docs: added metadata and auth flow
pagopa/oneidentity pull request #178
Opened 2024-07-15 13:13 UTC by himazawa

2024-07-17 08:11 UTC, BenitoVisone requested changes
I suppose that in the `auth_flow` diagram we're missing two interactions between steps **6** and **7**:

1. `update SAMLSession` record with the `SAMLResponse` parameter after the redirect POST on the `saml/acs` endpoint
2. `init OIDCSession` record after successful issuing of the `authorization_code`

*chore*: maybe it could be useful to add the `/token` POST request after the step 7. to make init of `AccessTokenSession Record` more explicit

2024-10-11 13:56 UTC, BenitoVisone reviewed
1. In the `auth_flow` I would connect the `/token` to the `API Gateway` instead of directly to `oneid-ecs-core`
2. In the `metadata_flow` I would add the Parameter Store dependency because the lambda will need it to sign and public the metadata with the certificate

2024-12-06 13:35 UTC, sebbalex commented on docs/diagrams/src/classes.d2
> +  identityServices {
```suggestion
  parameterStore: {
    icon: ../icons/paramstore.svg 
  }

  github: {
    icon: ../icons/github.png
  }

  identityServices: {
```

2024-12-06 13:35 UTC, sebbalex commented on docs/diagrams/src/infra.d2
> +  parameterStore {
```suggestion
  parameterStore: {
```

2024-12-06 13:35 UTC, sebbalex commented on docs/diagrams/src/auth_flow.d2
> +  parameterStore {
```suggestion
  dynamoDB: {
   class: dynamo
  }

  parameterStore: {
```

2024-12-06 13:35 UTC, sebbalex commented on docs/diagrams/src/metadata_flow.d2
> +  dynamoDB :{
```suggestion
  dynamoDB: {
```

2024-12-06 13:35 UTC, sebbalex commented on docs/diagrams/src/auth_flow.d2
> +  dynamoDB :{
```suggestion
  dynamoDB: {
```

2025-01-07 11:10 UTC, sebbalex commented
@himazawa @BenitoVisone I think we're all set here, can we merge it?

2025-01-08 13:50 UTC, BenitoVisone submitted a review, later dismissed

2026-07-27 15:07 UTC, sebbalex commented
Closing as stale, feel free to reopen it

2026-07-27 15:07 UTC, closed without merging