feat: [OI-204] vite migration
pagopa/oneidentity pull request #446
Opened 2024-10-18 08:36 UTC by mmoio

2024-10-21 15:28 UTC, sebbalex requested changes
Env file should respect the short environment names. This is mostly due to CIs which use this mapping to run trough envs.
So, I suggest to rename back `.env.production` to `.env.prod` and `.env.development` to `.env.dev`

2024-10-22 07:15 UTC, mmoio commented
> Env file should respect the short environment names. This is mostly due to CIs which use this mapping to run trough envs. So, I suggest to rename back `.env.production` to `.env.prod` and `.env.development` to `.env.dev`

I'should ve explained this changes better in the pr description, but vite uses some defaults when loading env files, some documentation regarding this argument in this page https://vite.dev/guide/env-and-mode. One of this default behaviours is loading a .env.development in a dev environment, and .env.production when building.
I will need to make some changes regarding the uat environment as well creating a custom mode in the future,.

2024-11-06 08:58 UTC, mmoio commented
> Env file should respect the short environment names. This is mostly due to CIs which use this mapping to run trough envs. So, I suggest to rename back `.env.production` to `.env.prod` and `.env.development` to `.env.dev`

For simplicity sake, I've changed back the environment files back to the original names, so to keep the pipeline environments coherent with the other parts of the project.
The only remaining change is renaming .env.local to .env.development, since is the one loaded by default by vite during development. A file .env.local is instead always loaded by vite and the defined variables in this file are overridden only if there is a more specific env file is loaded

2024-11-12 14:03 UTC, sebbalex commented
> > Env file should respect the short environment names. This is mostly due to CIs which use this mapping to run trough envs. So, I suggest to rename back `.env.production` to `.env.prod` and `.env.development` to `.env.dev`
> 
> For simplicity sake, I've changed back the environment files back to the original names, so to keep the pipeline environments coherent with the other parts of the project. The only remaining change is renaming .env.local to .env.development, since is the one loaded by default by vite during development. A file .env.local is instead always loaded by vite and the defined variables in this file are overridden only if there is a more specific env file is loaded

Thanks for the clarification, now I have a more comprehensive view.
We can keep `.env.development` for local environment, since it is a local development file it doesn't need to have specific naming.
We should fix `.env.dev` because of its conflicts inside.
And eventually, we can think to have a `.env.local` file to gather all the common variables among different environment in it.

[Here you can find](https://github.com/pagopa/oneidentity/blob/1c66cc8a9cecd63aac83aef92681779835f8a86f/.github/workflows/deploy-fe-ci.yaml#L57) the deployment pipeline which will build and ship the frontend stuff.

This line will load the environment from matrix (which it can be one from "dev|uat|prod", line 17) and build the app:
`export $(grep -v ^# .env.${{ github.event.inputs.environment }} | xargs) && yarn build`

2024-11-14 11:27 UTC, sebbalex commented on .github/workflows/deploy-fe-ci.yaml
> +              yarn build --mode
```suggestion
              yarn build --mode dev
```

2024-11-15 11:48 UTC, sebbalex commented on .github/workflows/deploy-fe-ci.yaml
>              aws s3 sync build s3://${{ vars.ASSETS_BUCKET_NAME }}
```suggestion
            aws s3 sync dist s3://${{ vars.ASSETS_BUCKET_NAME }}
```

2024-11-15 11:55 UTC, sebbalex approved these changes

2024-11-15 11:55 UTC, merged